WalletApp.Web/Models/ViewModels/TransactionsListViewModel.cs
using WalletApp.Web.Models.Domain;

namespace WalletApp.Web.Models.ViewModels
{
    public class TransactionsListViewModel
    {
        public User User { get; set; }
        public List<Transaction> Transactions { get; set; }
    }
}

WalletApp.Web/Controllers/TransactionController.cs
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WalletApp.Web.Data;
using WalletApp.Web.Models.Domain;
using WalletApp.Web.Models.ViewModels;


namespace WalletApp.Web.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TransactionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TransactionController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet("user/{userId}")]
        public async Task<IActionResult> TransactionsList(int userId)
        {
            var user = await _context.Users
                .Include(u => u.Transactions)
                .FirstOrDefaultAsync(u => u.Id == userId);

            if (user == null)
            {
                return NotFound();
            }

            var transactions = user.Transactions
                .OrderByDescending(t => t.Date)
                .Take(10)
                .ToList();

            var viewModel = new TransactionsListViewModel
            {
                User = user,
                Transactions = transactions
            };

            return View(viewModel);
        }

        [HttpGet("transaction/{id}")]
        public async Task<IActionResult> TransactionDetail(int id)
        {
            var transaction = await _context.Transactions.FirstOrDefaultAsync(t => t.Id == id);

            if (transaction == null)
            {
                return NotFound("Transaction not found!");
            }

            return View(transaction);
        }

        // GET: api/transaction
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Transaction>>> GetTransactions(int? userId)
        {
            IQueryable<Transaction> query = _context.Transactions;

            if (userId.HasValue)
            {
                query = query.Where(t => t.UserId == userId);
            }

            var transactions = await query.ToListAsync();
            return Ok(transactions);
        }

        // GET: api/transaction/{id}
        [HttpGet("{id}")]
        public async Task<ActionResult<Transaction>> GetTransaction(int id)
        {
            var transaction = await _context.Transactions.FindAsync(id);

            if (transaction == null)
            {
                return NotFound("Transaction not found!");
            }

            return Ok(transaction);
        }

        // POST: api/transaction
        [HttpPost]
        public async Task<ActionResult<Transaction>> Create(Transaction transaction)
        {
            if (!Enum.IsDefined(typeof(TransactionType), transaction.Type))
                return BadRequest("Invalid transaction type!");

            if (transaction.Title.Length == 0)
                return BadRequest("Title can't be empty!");

            transaction.Icon = FormatHexColor(transaction.Icon);

            _context.Transactions.Add(transaction);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetTransaction), new { id = transaction.Id }, transaction);
        }

        // PUT: api/transaction/{id}
        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, Transaction updatedTransaction)
        {
            if (id != updatedTransaction.Id)
            {
                return BadRequest("TransactionIdMismatch");
            }

            if (!Enum.IsDefined(typeof(TransactionType), updatedTransaction.Type))
                return BadRequest("Invalid transaction type!");

            if (updatedTransaction.Title.Length == 0)
                return BadRequest("Title can't be empty!");

            updatedTransaction.Icon = FormatHexColor(updatedTransaction.Icon);

            _context.Entry(updatedTransaction).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TransactionExists(id))
                {
                    return NotFound("Transaction not found!");
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // DELETE: api/transactions/{id}
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction == null)
            {
                return NotFound("Transaction not found!");
            }

            _context.Transactions.Remove(transaction);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool TransactionExists(int id)
        {
            return _context.Transactions.Any(e => e.Id == id);
        }

        private string FormatHexColor(string icon)
        {
            Regex hexWithoutHashtag = new Regex("^(([0-7][0-9A-Fa-f]){3}|([0-7][0-9A-Fa-f]){6})$");
            Regex hexWithHashtag = new Regex("^#(([0-7][0-9A-Fa-f]){3}|([0-7][0-9A-Fa-f]){6})$");

            if (hexWithoutHashtag.IsMatch(icon))
            {
                return $"#{icon}";
            }
            else if (!hexWithHashtag.IsMatch(icon))
            {
                Random random = new Random();
                return $"#{random.Next(0, 128):X2}{random.Next(0, 128):X2}{random.Next(0, 128):X2}";
            }
            return icon;
        }
    }
}

WalletApp.Web/Views/Transaction/TransactionDetail.cshtml
@using System.Globalization
@using System.Runtime.InteropServices.JavaScript
@model WalletApp.Web.Models.Domain.Transaction

@{
}

<div class="container mt-5">
    <div class="card text-center">
        <div class="card-header">
            @if (Model.Type == 0)
            {
                <h1 class="display-5 fw-bold">+$@Model.Amount </h1>
            }
            else
            {
                <h1 class="display-5 fw-bold">$@Model.Amount </h1>
            }
            <small class="text-muted">@Model.Title</small>
            <div>
                @Model.Date.ToString("MMMM d, yyyy", new CultureInfo("en-US"));
            </div>
        </div>
    </div>
    <div class="card-body">
        @if (Model.Pending == true)
        {
            <h5 class="card-title">Status: Pending</h5>
        }
        else
        {
            <h5 class="card-title">Status: Approved</h5>
        }
        <p class="card-text">@Model.Description</p>
        @if (Model.AuthorizedUser != null)
        {
            <p class="card-text">From: @Model.AuthorizedUser</p>
        }
    </div>

    <div class="card-footer">
        @{
            if (Model.Type == 0)
            {
                <div>
                    Total: +$@Model.Amount
                </div>
            }
            else
            {
                <div>
                    Total: $@Model.Amount
                </div>
            }
        } 
    </div>
</div>

WalletApp.Web/Views/Transaction/TransactionsList.cshtml
@using System.Globalization
@model WalletApp.Web.Models.ViewModels.TransactionsListViewModel

<div class="d-flex">
    <div class="d-flex flex-column">
        <div class="card text-bg-secondary mb-2" style="max-width: 18rem;">
            <div class="card-header">Card Balance</div>
            <div class="card-body">
                <h5 class="card-title fw-bold">$@Model.User.CardBalance</h5>
                <p class="card-text">Available: $@((1500 - Model.User.CardBalance).ToString())</p>
            </div>
        </div>
        <div class="card text-bg-secondary mb-2" style="max-width: 18rem;">
            <div class="card-header">Daily Points</div>
            <div class="card-body">
                <h5 class="card-title fw-bold">@Model.User.DailyPoints points</h5>
            </div>
        </div>
    </div>

    <div class="card text-bg-secondary ms-2 mb-2 d-flex flex-column justify-content-between" style="max-width: 18rem; flex-grow: 1;">
        <div class="card-header">No Payment Due</div>
        <div class="card-body d-flex flex-column justify-content-between">
            <h5 class="card-title">You've paid your @(DateTime.Now.ToString("MMMM", new System.Globalization.CultureInfo("en-US"))) balance</h5>

            <div class="mt-auto d-flex justify-content-end align-items-end">
                <span style="font-size: 3rem; color: black;">&#10003;</span>
            </div>
        </div>
    </div>
</div>

<h2>Latest Transactions</h2>
<div class="list-group">
    @foreach (var transaction in Model.Transactions)
    {
        <a href="@Url.Action("TransactionDetail", "Transaction", new { id = transaction.Id })" class="list-group-item d-flex justify-content-between align-items-center">
            <div class="d-flex">

                <div class="me-3 d-flex align-items-center justify-content-center" style="width: 50px; height: 50px; background-color: @transaction.Icon; border-radius: 8px;">
                    <i class="bi bi-cash-stack text-white"></i>
                </div>

                <div>
                    <h5 class="mb-0">@transaction.Title</h5>
                    @{
                        if (transaction.Pending == true)
                        {
                            <p class="mb-0 text-muted">Pending - @transaction.Description</p>
                        }
                        else
                        {
                            <p class="mb-0 text-muted">@transaction.Description</p>
                        }
                    }
                    <p class="mb-0 text-muted">
                        @{
                            var daysAgo = (DateTime.Now - transaction.Date).TotalDays;
                            string output;

                            if (daysAgo < 7)
                            {
                                if (transaction.AuthorizedUser != null)
                                {
                                    output = $"{transaction.AuthorizedUser} - {transaction.Date.ToString("dddd", new CultureInfo("en-US"))}";
                                }
                                else
                                {
                                    output = $"{transaction.Date.ToString("dddd", new CultureInfo("en-US"))}";
                                }
                            }
                            else
                            {
                                if (transaction.AuthorizedUser != null)
                                {
                                    output = $"{transaction.AuthorizedUser} - {transaction.Date.ToString("MMMM d, yyyy", new CultureInfo("en-US"))}";
                                }
                                else
                                {
                                    output = $"{transaction.Date.ToString("MMMM d, yyyy", new CultureInfo("en-US"))}";
                                }
                            }
                            @output
                        }
                    </p>
                </div>
            </div>

            <div>
                @if (transaction.Type == 0)
                {
                    <h5 class="fw-bold">+$@transaction.Amount</h5>
                }
                else
                {
                    <h5 class="fw-bold">$@transaction.Amount</h5>
                }


            </div>
        </a>
    }
</div>